import pyautogui
import time

class BlackDesertAuto:

    def __init__(self):
        self.main_skill = "slash"
        self.sub_skill = "kick"
        self.summon_skill = "summon_spirit"
        self.move_skill = "dash"
        self.other_skills = ["magic_arrow", "fireball"]

    def start(self):
        while True:
            # 使用主要技能
            pyautogui.press(self.main_skill)
            time.sleep(0.5)

            # 使用次要技能
            if pyautogui.is_pressed("shift"):
                pyautogui.press(self.sub_skill)
                time.sleep(0.5)

            # 使用召喚技能
            if pyautogui.is_pressed("ctrl"):
                pyautogui.press(self.summon_skill)
                time.sleep(0.5)

            # 使用移動技能
            if pyautogui.is_pressed("space"):
                pyautogui.press(self.move_skill)
                time.sleep(0.5)

            # 使用其他技能
            for skill in self.other_skills:
                if pyautogui.is_pressed(skill):
                    pyautogui.press(skill)
                    time.sleep(0.5)


if __name__ == "__main__":
    black_desert_auto = BlackDesertAuto()
    black_desert_auto.start()

